void printWebPage(EthernetClient cl){
  cl.println("<!DOCTYPE html> ");
  cl.println("<html>");
  cl.println("    <head>");
  cl.println("        <title>AxtonTech Illumnate the Night</title>");
  cl.println("        <script>");
  cl.println("      		_degree10  = '';");
  cl.println("      		_degree45  = '';");
  cl.println("      		_degree130 = '';");
  cl.println("          _power     = '';");
  cl.println("          ");
  cl.println("          _degree10_state  = 0;");
  cl.println("          _degree45_state  = 0;");
  cl.println("          _degree130_state = 0;");
  cl.println("          _power_state     = 0;");
  cl.println("          function XMLToString(oXML) {   ");
  cl.println("              if (window.ActiveXObject) {     ");
  cl.println("                  return oXML.xml;  //if IE ");
  cl.println("              } else {     ");
  cl.println("                  return (new XMLSerializer()).serializeToString(oXML);   //other browsers");
  cl.println("              } ");
  cl.println("          }");
  cl.println("      		function GetArduinoIO()");
  cl.println("      		{");
  cl.println("      			nocache = '&nocache=' + Math.random() * 1000000;");
  cl.println("      			var request = new XMLHttpRequest();");
  cl.println("      			request.onreadystatechange = function()");
  cl.println("      			{");
  cl.println("      				if (this.readyState == 4) {");
  cl.println("      					if(this.status == 200) {");
  cl.println("      						if (this.responseXML != null) {");
  cl.println("      							//alert(XMLToString(this.responseXML));");
  cl.println("                      //alert(this.responseXML.documentElement.getElementsByTagName('power'));");
  cl.println("                      //alert(this.responseXML.getElementsByTagName('power')[0].childNodes[0].nodeValue);");
  cl.println("         							if (this.responseXML.getElementsByTagName('power')[0].childNodes[0].nodeValue === 'off') {");
  cl.println("      								document.getElementById('power').innerHTML = 'Power Off';");
  cl.println("      								_power_state     = 0;");
  cl.println("      								_degree10_state  = 0;");
  cl.println("      								_degree45_state  = 0;");
  cl.println("      								_degree130_state = 0;");
  cl.println("      							}else{");
  cl.println("      								  _power_state = 1;");
  cl.println("      								  document.getElementById('power').innerHTML = 'Power On';");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree10')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree10').innerHTML = 'Zoom 10 Degrees On';");
  cl.println("          								_degree10_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree10').innerHTML = 'Zoom 10 Degrees Off';");
  cl.println("          								_degree10_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree45')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree45').innerHTML = 'Zoom 45 Degrees On';");
  cl.println("          								_degree45_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree45').innerHTML = 'Zoom 45 Degrees Off';");
  cl.println("          								_degree45_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree130')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree130').innerHTML = 'Zoom 130 Degrees On';");
  cl.println("          								_degree130_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree130').innerHTML = 'Zoom 130 Degrees Off';");
  cl.println("          								_degree130_state = 0;");
  cl.println("          							}");
  cl.println("      						  }");
  cl.println("      ");
  cl.println("      						}");
  cl.println("      					}");
  cl.println("      				}");
  cl.println("      			}");
  cl.println("      			// send HTTP GET request with LEDs to switch on/off if any");
  cl.println("      			request.open('GET', 'ajax_inputs' + _degree10 + _degree45 + _degree130 + _power + nocache, true);");
  cl.println("      			request.send(null);");
  cl.println("      			setTimeout('GetArduinoIO()', 1000);");
  cl.println("        		_degree10  = '';");
  cl.println("      	  	_degree45  = '';");
  cl.println("      		  _degree130 = '';");
  cl.println("            _power     = '';");
  cl.println("      ");
  cl.println("      		}");
  cl.println("      ");
  cl.println("      		function GetButton()");
  cl.println("      		{");
  cl.println("      			if (_power_state === 0) {");
  cl.println("      				_power_state     = 1;");
  cl.println("      				_degree10_state  = 1;");
  cl.println("      				_degree45_state  = 1;");
  cl.println("      				_degree130_state = 1;");
  cl.println("      				_power       = '&power=1';");
  cl.println("      				_degree10    = '&degree10=1';");
  cl.println("      				_degree45    = '&degree45=1';");
  cl.println("      				_degree130   = '&degree130=1';");
  cl.println("      			}else {");
  cl.println("      				_power_state = 1;");
  cl.println("      				_power       = '&power=0';");
  cl.println("      				");
  cl.println("        			if (_degree10_state === 1) {");
  cl.println("        				_degree10_state = 0;");
  cl.println("        				_degree10 = '&degree10=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree10_state = 1;");
  cl.println("        				_degree10 = '&degree10=1';");
  cl.println("        			}");
  cl.println("        			if (_degree45_state === 1) {");
  cl.println("        				_degree45_state = 0;");
  cl.println("        				_degree45 = '&degree45=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree45_state = 1;");
  cl.println("        				_degree45 = '&degree45=1';");
  cl.println("        			}");
  cl.println("        			if (_degree130_state === 1) {");
  cl.println("        				_degree130_state = 0;");
  cl.println("        				_degree130 = '&degree130=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree130_state = 1;");
  cl.println("        				_degree130 = '&degree130=1';");
  cl.println("        			}");
  cl.println("      		  }");
  cl.println("      		}");
  cl.println("	      </script>");
  cl.println("");
  cl.println("	<style>");
  cl.println("		.IO_box {");
  cl.println("			float: left;");
  cl.println("			margin: 0 20px 20px 0;");
  cl.println("			border: 1px solid blue;");
  cl.println("			padding: 0 5px 0 5px;");
  cl.println("			width: 120px;");
  cl.println("		}");
  cl.println("		h1 {");
  cl.println("			font-size: 120%;");
  cl.println("			color: blue;");
  cl.println("			margin: 0 0 10px 0;");
  cl.println("		}");
  cl.println("		h2 {");
  cl.println("			font-size: 85%;");
  cl.println("			color: #5734E6;");
  cl.println("			margin: 5px 0 5px 0;");
  cl.println("		}");
  cl.println("		p, form, button {");
  cl.println("			font-size: 80%;");
  cl.println("			color: #252525;");
  cl.println("		}");
  cl.println("		.small_text {");
  cl.println("			font-size: 70%;");
  cl.println("			color: #737373;");
  cl.println("		}");
  cl.println("	</style>");
  cl.println("    </head>");
  cl.println("    <body onload='GetArduinoIO()'>");
  cl.println("        <h1>Illumination Controls</h1>");
  cl.println("		<div class='IO_box' >");
  cl.println("			<h2>Control Buttons</h2>");
  cl.println("				<button type='button' class='degree' id='degree10'  onclick='GetButton()'  >Zoom 10  Degrees Off  </button><br /><br />");
  cl.println("				<button type='button' class='degree' id='degree45'  onclick='GetButton()'  >Zoom 45  Degrees Off  </button><br /><br />");
  cl.println("				<button type='button' class='degree' id='degree130' onclick='GetButton()'  >Zoom 130 Degrees Off  </button><br /><br />");
  cl.println("				<button type='button' class='power'  id='power'     onclick='GetButton()'  >Power Off             </button><br /><br />");
  cl.println("		</div>");
  cl.println("    </body>");
  cl.println("</html>");
}
