void nitelite_ui(EthernetClient cl){ 
cl.println("<!DOCTYPE html> ");
cl.println("<html>");
cl.println("  <head>");
cl.println("        <title>AxtonTech Illumnate the Night</title>");
cl.println("  <style>");
cl.println("    body{");
cl.println("      position: absolute;");
cl.println("      display: block;");
cl.println("      top: 0;");
cl.println("      left: 0;");
cl.println("      min-height: 100%;");
cl.println("      min-width: 100%;");
cl.println("      margin: 0;");
cl.println("      padding: 0;");
cl.println("      color: #868686;");
cl.println("      background: #D3D4D6;");
cl.println("      font-family: arial, sans-serif;");
cl.println("      box-sizing: border-box;");
cl.println("    }");
cl.println("    h1{");
cl.println("      font-size: 20px;");
cl.println("      font-weight: normal;");
cl.println("    }");
cl.println("    h2{");
cl.println("      position: relative;");
cl.println("      min-width: 120px;");
cl.println("      margin: -10px 0 .5em 0;");
cl.println("      float: left;");
cl.println("      color: #333;");
cl.println("    }");
cl.println("    h2 small {");
cl.println("      font-size: 0.5em;");
cl.println("      font-weight: normal;");
cl.println("      color: #aaa;");
cl.println("      position: absolute;");
cl.println("      bottom: -1.2em;");
cl.println("      width: 130px;");
cl.println("      left: 0;");
cl.println("    }");
cl.println("    button{");
cl.println("      margin: 0;");
cl.println("      cursor: pointer;");
cl.println("    }");
cl.println("    label,");
cl.println("    input{");
cl.println("      cursor: pointer;");
cl.println("    }");
cl.println("    strong{");
cl.println("      display: block;");
cl.println("      float: left;");
cl.println("      margin: 8px 20px 0 0;");
cl.println("    }");
cl.println("    strong.space{ ");
cl.println("      display: inline-block;");
cl.println("      margin-bottom: 5px;");
cl.println("    }");
cl.println("    #frame{ ");
cl.println("      display: block;");
cl.println("      width: 95%;");
cl.println("      max-width: 600px;");
cl.println("      min-width: 425px;");
cl.println("      margin: 20px auto;");
cl.println("      padding: 0 25px 25px 25px;");
cl.println("      background-color: #fff; ");
cl.println("      box-sizing: border-box;");
cl.println("    }");
cl.println("    #header{");
cl.println("      padding: 21px 0 15px 0;");
cl.println("      border-top: 4px solid #73bc43;");
cl.println("      border-bottom: 2px #ddd solid;");
cl.println("    }");
cl.println("    #header h1{");
cl.println("      display: inline-block;");
cl.println("      margin: 0;");
cl.println("    }");
cl.println("    #header img{");
cl.println("      margin-bottom: -12px;");
cl.println("    }");
cl.println("    #logoWrapper{");
cl.println("      display: inline-block;");
cl.println("    }");
cl.println("    #content{");
cl.println("      padding-top: 25px;");
cl.println("    }");
cl.println("");
cl.println("");
cl.println("    .product{");
cl.println("      padding: 25px 2px; ");
cl.println("      margin-bottom: 25px;");
cl.println("    }");
cl.println("    .product.xlr{");
cl.println("      border-left: 4px solid #CC4623; ");
cl.println("    }");
cl.println("    .product.zoom{");
cl.println("      border-left: 4px solid #73bc43; ");
cl.println("    }");
cl.println("    .product.hybrid{");
cl.println("      border-left: 4px solid #507590; ");
cl.println("    }");
cl.println("    .toggleWrap{");
cl.println("      float: left;");
cl.println("      margin-left: 30px");
cl.println("    }");
cl.println("    .drawer{");
cl.println("      height: 0;");
cl.println("      padding-left: 20px;");
cl.println("      overflow: hidden;");
cl.println("      transition: height 1s;");
cl.println("      clear: both;");
cl.println("    }");
cl.println("    .open #xlrControls{");
cl.println("      height: 60px;");
cl.println("    }");
cl.println("    .open #zoomControls{");
cl.println("      height: 204px;");
cl.println("    }");
cl.println("    .open #hybridControls{");
cl.println("      height: 100px;");
cl.println("    }");
cl.println("    .toggleWrap button{");
cl.println("      position: relative;");
cl.println("      width: 150px;");
cl.println("      height: 35px;");
cl.println("    }");
cl.println("    .toggleWrap button:after{");
cl.println("      content: 'Manual Control';");
cl.println("      position: absolute;");
cl.println("      top: 7px;");
cl.println("      left: 0;");
cl.println("      height: 100%;");
cl.println("      width: 100%;");
cl.println("      text-align: center; ");
cl.println("    }");
cl.println("    .open .toggleWrap button:after{");
cl.println("      content: 'Auto Control';");
cl.println("    }");
cl.println("");
cl.println("");
cl.println("    .cut{");
cl.println("      padding: 15px 0 0 0;");
cl.println("      clear: both;");
cl.println("    }");
cl.println("");
cl.println("");
cl.println("");
cl.println("");
cl.println("    /** Form controlls **/");
cl.println("");
cl.println("    .power {");
cl.println("      position: relative;");
cl.println("      display: block;");
cl.println("      float: left;");
cl.println("      width: 1em;");
cl.println("      height: 1em;");
cl.println("      margin: -5px 10px !important;");
cl.println("      border-radius: 50% !important;");
cl.println("    }");
cl.println("    .power:before {");
cl.println("      content: '';");
cl.println("      position: absolute;");
cl.println("      display: block;");
cl.println("      top: 1px;");
cl.println("      left: 50%;");
cl.println("      width: 4px;");
cl.println("      height: 45%;");
cl.println("      margin-left: -5px;");
cl.println("      border-radius: 5px;");
cl.println("      border-left: solid 3px #eee;");
cl.println("      border-right: solid 3px #eee;");
cl.println("      background-color: #CC4623;");
cl.println("      z-index: 1;");
cl.println("    }");
cl.println("    .power:after {");
cl.println("      content: '';");
cl.println("      position: absolute;");
cl.println("      display: block;");
cl.println("      top: 15%;");
cl.println("      left: 12%;");
cl.println("      width: 75%;");
cl.println("      height: 75%;");
cl.println("      border: solid #CC4623;");
cl.println("      border-radius: 100%;");
cl.println("      box-sizing: border-box;");
cl.println("    }");
cl.println("    input:checked + .power:before{");
cl.println("      background-color: #73bc43;");
cl.println("    }");
cl.println("    input:checked + .power:after{");
cl.println("      border-color: #73bc43;");
cl.println("    }");
cl.println("    input[type=checkbox]{");
cl.println("      display: none;");
cl.println("    }");
cl.println("");
cl.println("");
cl.println("");
cl.println("    .slider{");
cl.println("      position: relative;");
cl.println("      width: 55%;");
cl.println("      padding-top: 30px;");
cl.println("    }");
cl.println("    .slider input{");
cl.println("      width: 100%;");
cl.println("    }");
cl.println("    .slider span{");
cl.println("      position: absolute;");
cl.println("      display: block;");
cl.println("      width: 88px; ");
cl.println("      text-align: center;");
cl.println("      font-size: .75em;");
cl.println("    }");
cl.println("    #sliderlabel--narrow{");
cl.println("      top: 0;");
cl.println("      left: 0px;");
cl.println("      text-align: left;");
cl.println("    }");
cl.println("    #sliderlabel--medium{");
cl.println("      top: 0;");
cl.println("      left: 50%; ");
cl.println("      margin-left: -44px;");
cl.println("    }");
cl.println("    #sliderlabel--wide{");
cl.println("      top: 0;");
cl.println("      right: 0px;");
cl.println("      text-align: right;");
cl.println("    }");
cl.println("");
cl.println("");
cl.println("");
cl.println("    .hybridLights label{");
cl.println("      display: block;");
cl.println("    }");
cl.println("    .hybridStong{");
cl.println("      display: block;");
cl.println("      float: none;");
cl.println("    }");
cl.println("");
cl.println(".onoffswitch {");
cl.println("    position: relative; width: 117px;");
cl.println("    -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;");
cl.println("    float: left;");
cl.println("}");
cl.println(".onoffswitch-checkbox {");
cl.println("    display: none;");
cl.println("}");
cl.println(".onoffswitch-label {");
cl.println("    display: block; overflow: hidden; cursor: pointer;");
cl.println("    border: 2px solid #666666; border-radius: 30px;");
cl.println("}");
cl.println(".onoffswitch-inner {");
cl.println("    width: 200%; margin-left: -100%;");
cl.println("    -moz-transition: margin 0.3s ease-in 0s; -webkit-transition: margin 0.3s ease-in 0s;");
cl.println("    -o-transition: margin 0.3s ease-in 0s; transition: margin 0.3s ease-in 0s;");
cl.println("}");
cl.println(".onoffswitch-inner:before, .onoffswitch-inner:after {");
cl.println("    float: left; width: 50%; height: 30px; padding: 0; line-height: 30px;");
cl.println("    font-size: 19px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;");
cl.println("    -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box;");
cl.println("    border-radius: 30px;");
cl.println("    box-shadow: 0px 15px 0px rgba(0,0,0,0.08) inset;");
cl.println("}");
cl.println(".onoffswitch-inner:before {");
cl.println("    content: 'High';");
cl.println("    padding-left: 19px;");
cl.println("    background-color: #CC4623; color: #FFFFFF;");
cl.println("    border-radius: 30px 0 0 30px;");
cl.println("}");
cl.println(".onoffswitch-inner:after {");
cl.println("    content: 'Low';");
cl.println("    padding-right: 19px;");
cl.println("    background-color: #FFFFFF; color: #666666;");
cl.println("    text-align: right;");
cl.println("    border-radius: 0 30px 30px 0;");
cl.println("}");
cl.println(".onoffswitch-switch {");
cl.println("    width: 30px; margin: 0px;");
cl.println("    background: #FFFFFF;");
cl.println("    border: 2px solid #666666; border-radius: 30px;");
cl.println("    position: absolute; top: 0; bottom: 0; right: 83px;");
cl.println("    -moz-transition: all 0.3s ease-in 0s; -webkit-transition: all 0.3s ease-in 0s;");
cl.println("    -o-transition: all 0.3s ease-in 0s; transition: all 0.3s ease-in 0s; ");
cl.println("    background-image: -moz-linear-gradient(center top, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0) 80%); ");
cl.println("    background-image: -webkit-linear-gradient(center top, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0) 80%); ");
cl.println("    background-image: -o-linear-gradient(center top, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0) 80%); ");
cl.println("    background-image: linear-gradient(center top, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0) 80%);");
cl.println("    box-shadow: 0 1px 1px white inset;");
cl.println("}");
cl.println(".onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {");
cl.println("    margin-left: 0;");
cl.println("}");
cl.println(".onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {");
cl.println("    right: 0px; ");
cl.println("}");
cl.println("label.power,");
cl.println("button {");
cl.println("  -moz-box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  -webkit-box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  background: -webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );");
cl.println("  background: -moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );");
cl.println("  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');");
cl.println("  background-color: #ededed;");
cl.println("  -webkit-border-top-left-radius: 6px;");
cl.println("  -moz-border-radius-topleft: 6px;");
cl.println("  border-top-left-radius: 6px;");
cl.println("  -webkit-border-top-right-radius: 6px;");
cl.println("  -moz-border-radius-topright: 6px;");
cl.println("  border-top-right-radius: 6px;");
cl.println("  -webkit-border-bottom-right-radius: 6px;");
cl.println("  -moz-border-radius-bottomright: 6px;");
cl.println("  border-bottom-right-radius: 6px;");
cl.println("  -webkit-border-bottom-left-radius: 6px;");
cl.println("  -moz-border-radius-bottomleft: 6px;");
cl.println("  border-bottom-left-radius: 6px;");
cl.println("  text-indent: 0;");
cl.println("  border: 1px solid #dcdcdc;");
cl.println("  display: inline-block;");
cl.println("  color: #777777;");
cl.println("  font-family: arial;");
cl.println("  font-size: 15px;");
cl.println("  font-weight: bold;");
cl.println("  font-style: normal;");
cl.println("  text-decoration: none;");
cl.println("  text-align: center;");
cl.println("  text-shadow: 1px 1px 0px #ffffff;");
cl.println("  padding: 8px 10px;");
cl.println("  margin-top: -15px;");
cl.println("  outline: none;");
cl.println("}");
cl.println("button:hover {");
cl.println("	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );");
cl.println("	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );");
cl.println("	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');");
cl.println("	background-color:#dfdfdf;");
cl.println("}button:active {");
cl.println("	position:relative;");
cl.println("	top:1px;");
cl.println("}");
cl.println("select,");
cl.println("select option,");
cl.println("label.power,");
cl.println("button {");
cl.println("  -moz-box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  -webkit-box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  box-shadow: inset 0px 1px 0px 0px #ffffff;");
cl.println("  background: -webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );");
cl.println("  background: -moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );");
cl.println("  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');");
cl.println("  background-color: #ededed;");
cl.println("  -webkit-border-top-left-radius: 6px;");
cl.println("  -moz-border-radius-topleft: 6px;");
cl.println("  border-top-left-radius: 6px;");
cl.println("  -webkit-border-top-right-radius: 6px;");
cl.println("  -moz-border-radius-topright: 6px;");
cl.println("  border-top-right-radius: 6px;");
cl.println("  -webkit-border-bottom-right-radius: 6px;");
cl.println("  -moz-border-radius-bottomright: 6px;");
cl.println("  border-bottom-right-radius: 6px;");
cl.println("  -webkit-border-bottom-left-radius: 6px;");
cl.println("  -moz-border-radius-bottomleft: 6px;");
cl.println("  border-bottom-left-radius: 6px;");
cl.println("  text-indent: 0;");
cl.println("  border: 1px solid #dcdcdc;");
cl.println("  display: inline-block;");
cl.println("  color: #777777;");
cl.println("  font-family: arial;");
cl.println("  font-size: 15px;");
cl.println("  font-weight: bold;");
cl.println("  font-style: normal;");
cl.println("  text-decoration: none;");
cl.println("  text-align: center;");
cl.println("  text-shadow: 1px 1px 0px #ffffff;");
cl.println("  padding: 8px 10px;");
cl.println("  margin-top: -15px;");
cl.println("  outline: none;");
cl.println("}");
cl.println("select:hover,");
cl.println("button:hover {");
cl.println("	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );");
cl.println("	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );");
cl.println("	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');");
cl.println("	background-color:#dfdfdf;");
cl.println("}button:active {");
cl.println("	position:relative;");
cl.println("	top:1px;");
cl.println("}");
cl.println("select::-ms-expand {");
cl.println("    display: none; /* hide default arrow in IE10 */");
cl.println("}");
cl.println("select {");
cl.println("    width: 50%; /* Set width. Do not set height else it will fail in IE8-10. Use padding for height. */");
cl.println("    font-weight: normal;");
cl.println("    font-size: 1em;");
cl.println("    line-height:1.2em;");
cl.println("    margin: 0 0 10px;");
cl.println("    padding: 6px 0; /* use this to set a specific height for your dropdown (DO NOT use the attribute 'height') */");
cl.println("    border: 0 none;");
cl.println("    cursor: pointer;");
cl.println("    text-indent: 5px;");
cl.println("    text-overflow: '';");
cl.println("    -webkit-appearance: none; /* gets rid of default appearance in Webkit browsers*/");
cl.println("    -moz-appearance: none; /* Get rid of default appearance for older Firefox browsers */");
cl.println("    -ms-appearance: none; /* get rid of default appearance for IE8, 9 and 10*/");
cl.println("    appearance: none; ");
cl.println("}");
cl.println(".selectWrapper{");
cl.println("  position: relative;");
cl.println("  display: inline;");
cl.println("}");
cl.println(".selectArrow{");
cl.println("  border: solid 7px transparent;");
cl.println("  border-bottom: none;");
cl.println("  display: block;");
cl.println("  position: absolute;");
cl.println("  border-top-color: inherit;");
cl.println("  right: 9px;");
cl.println("  top: 6px;");
cl.println("}");
cl.println(".selectLine{");
cl.println("  border-left: solid 1px;");
cl.println("  display: block;");
cl.println("  position: absolute;");
cl.println("  right: 30px;");
cl.println("  top: -20%;");
cl.println("  height: 150%;");
cl.println("  opacity: .5;");
cl.println("}");
cl.println(".angles{");
cl.println("  position: relative;");
cl.println("  width: 320px;");
cl.println("  height: 100px;");
cl.println("  margin: 20px 0;");
cl.println("}");
cl.println("");
cl.println(".angleWrap{");
cl.println("  position: absolute;");
cl.println("  left: 0;");
cl.println("  top: 0; ");
cl.println("  height: 100%;");
cl.println("  cursor: pointer;");
cl.println("}");
cl.println(".angleUi:after{");
cl.println("  content: '';");
cl.println("  display: block;");
cl.println("  position: absolute;");
cl.println("  top: 5px;");
cl.println("  left: 5px;");
cl.println("  border-right-color: #fff !important;");
cl.println("}");
cl.println(".angleUi, .angleUi:after{");
cl.println("  border-left: none;");
cl.println("  border-bottom-right-radius: 30px;");
cl.println("  border-top-right-radius: 30px;");
cl.println("}");
cl.println(".angleUi{ ");
cl.println("  box-shadow: 5px 0px 16px 5px #fff;");
cl.println("}");
cl.println(".choosen .angleUi{");
cl.println("  border-right-color: #CC4623 !important;");
cl.println("  box-shadow: 8px 0px 6px -5px #CC4623;");
cl.println("}");
cl.println(".choosen .angleUi:after{");
cl.println("  border-right-color: #E6603D !important;");
cl.println("}");
cl.println(".range,");
cl.println(".angle {");
cl.println("  position: absolute;");
cl.println("  right: 0;");
cl.println("  font-size: .75em;");
cl.println("  text-align: right;");
cl.println("}");
cl.println(".angle{ ");
cl.println("  top: -1em;");
cl.println("}");
cl.println(".range{");
cl.println("  bottom: -1em;");
cl.println("}");
cl.println("#angle3{");
cl.println("  width: 33%;");
cl.println("");
cl.println("}");
cl.println("#angle3 .angleUi{");
cl.println("  border-top: solid transparent 50px;");
cl.println("  border-bottom: solid transparent 50px;");
cl.println("  border-right: solid 106px; ");
cl.println("}");
cl.println("#angle3 .angleUi:after{");
cl.println("  border-top: solid transparent 45px;");
cl.println("  border-bottom: solid transparent 45px;");
cl.println("  border-right: solid 99px;");
cl.println("}");
cl.println("#angle2{");
cl.println("  width: 66%;");
cl.println("}");
cl.println("#angle2 .angleUi{");
cl.println("  border-top: solid transparent 38px;");
cl.println("  border-bottom: solid transparent 38px;");
cl.println("  border-right: solid 211px;");
cl.println("  margin-top: 12px;");
cl.println("}");
cl.println("#angle2 .angleUi:after{");
cl.println("  border-top: solid transparent 33px;");
cl.println("  border-bottom: solid transparent 33px;");
cl.println("  border-right: solid 206px; ");
cl.println("  margin-top: 12px;");
cl.println("}");
cl.println("#angle1{");
cl.println("  width: 100%;");
cl.println("}");
cl.println("#angle1 .angleUi{");
cl.println("  border-top: solid transparent 25px;");
cl.println("  border-bottom: solid transparent 25px;");
cl.println("  border-right: solid 320px; ");
cl.println("  margin-top: 25px;");
cl.println("}");
cl.println("#angle1 .angleUi:after{");
cl.println("  border-top: solid transparent 20px;");
cl.println("  border-bottom: solid transparent 20px;");
cl.println("  border-right: solid 315px; ");
cl.println("  margin-top: 25px;");
cl.println("}");
cl.println("  </style>");
cl.println("");
cl.println("          <script>");
cl.println("          ");
cl.println("");
cl.println("          </script>");
cl.println("  </head>");
cl.println("    <body>");
cl.println("      <div id='frame'>");
cl.println("        <div id='header'> ");
//cl.println("          <div id='logoWrapper'><img width='234' height='67' title='' alt='' src='' /></div>");
cl.println("<div id='logoWrapper'><img width='234' height='67' title='' alt=''  src='data:image/png;base64,");
  for (int i=0;i<21;i++){
    cl.write(logo_raw[i]);
  }
cl.println("'> "); 
cl.println("          <h1>Professional<br /> IR Illuminators</h1>");
cl.println("        </div>");
cl.println("        <div id='content'>");
cl.println("");
if(digitalRead(io_jumper_illuminator1)==0 || digitalRead(io_jumper_illuminator2) == 0 || digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("          <div class='product xlr' id='xlr'>");
//cl.println("            <input type='checkbox' name='xlrPower' id='xlrPower' unchecked />");
//cl.println("            <label for='xlrPower' class='power'></label>");
cl.println("            <h2>XLR<small>Extreme Long Range</small></h2>");
cl.println("            <div class='toggleWrap'><button id='xlrToggle'></button></div>");
cl.println("            <div id='xlrControls' class='drawer'>");
cl.println("              <div class='cut'>");
cl.println("                <strong for=''>Beam:</strong>");
cl.println("                <div class='onoffswitch'>");
cl.println("                  <input type='checkbox' name='onoffswitch' class='onoffswitch-checkbox' id='xlrSwitch' checked>");
cl.println("                  <label class='onoffswitch-label' for='xlrSwitch'>");
cl.println("                      <div class='onoffswitch-inner'></div>");
cl.println("                      <div class='onoffswitch-switch'></div>");
cl.println("                  </label>");
cl.println("              </div>");
cl.println("              </div>");
cl.println("            </div>");
cl.println("          </div> ");
}
cl.println("");
if(digitalRead(io_jumper_illuminator2) == 0 || digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("          <div class='product zoom' id='zoom'>");
//cl.println("            <input type='checkbox' name='zoomPower' id='zoomPower' unchecked />");
//cl.println("            <label for='zoomPower' class='power'></label>");
cl.println("            <h2>Zoom<small>Variable Angels</small></h2>");
cl.println("            <div class='toggleWrap'><button id='zoomToggle'></button></div>");
cl.println("            <div id='zoomControls' class='drawer'>");
cl.println("              <strong class='space' for='zommAngle'>Angle/Range</strong>");
cl.println("              <div class='cut'>");
cl.println("                <div class='angles'> ");
cl.println("                  <div id='angle1' class='angleWrap'>");
cl.println("                    <div class='angleUi'></div>");
cl.println("                    <span class='angle'>Narrow<small> (10 deg)</small></span>");
cl.println("                    <span class='range'>Long Range</span>");
cl.println("                  </div> ");
cl.println("                  <div id='angle2' class='angleWrap'>");
cl.println("                    <div class='angleUi'></div>");
cl.println("                    <span class='angle'>Medium<small> (60 deg)</small></span>");
cl.println("                    <span class='range'>Medium Range</span>");
cl.println("                  </div>");
cl.println("                  <div id='angle3' class='angleWrap'>");
cl.println("                    <div class='angleUi'></div>");
cl.println("                    <span class='angle'>Wide<small> (130 deg)</small></span>");
cl.println("                    <span class='range'>Close Range</span>");
cl.println("                  </div>");
cl.println("                </div>");
cl.println("              </div>");
cl.println("            </div>");
cl.println("          </div> ");
}
cl.println("");
if(digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("          <div class='product hybrid' id='hybrid'>");
//cl.println("            <input type='checkbox' name='hybridPower' id='hybridPower' unchecked />");
//cl.println("            <label for='hybridPower' class='power'></label>");
cl.println("            <h2>Hybrid<small>IR + White Light</small></h2>");
cl.println("            <div class='toggleWrap'><button id='hybridToggle'></button></div>");
cl.println("            <div id='hybridControls' class='drawer'>");
cl.println("              <div class='cut'>");
cl.println("                <strong class='hybridStong' for='Lighting'>Lighting </strong>");
cl.println("                <div class='hybridLights'>");
cl.println("                  <label for='irlight'><input type='radio' name='light' id='irlight'>IR Light</label>");
cl.println("                  <label for='whiteLight'><input type='radio' name='light' id='whiteLight'>White Light</label>");
cl.println("                    <!-- <label for='alarm'><input type='radio' name='light' id='alarm'>Alarm - White Strobe</label> -->");
cl.println("                </div>");
cl.println("              </div>");
cl.println("            </div>");
cl.println("          </div> ");
}
cl.println("");
cl.println("        </div>");
cl.println("      </div>");
cl.println("      <script>");
cl.println("        var drawers = document.getElementsByClassName('product');");
cl.println("        var angleWrappers = document.getElementsByClassName('angleWrap');");
cl.println("        var xlrToggle = document.getElementById('xlrToggle');");
cl.println("        var zoomToggle= document.getElementById('zoomToggle');");
cl.println("        var hybridToggle = document.getElementById('hybridToggle');");
cl.println("        var xlrSwitch = document.getElementById('xlrSwitch');");
cl.println("        var controls = {");
cl.println("          'xlrToggle': document.getElementById('xlr'),");
cl.println("          'zoomToggle': document.getElementById('zoom'),");
cl.println("          'hybridToggle': document.getElementById('hybrid')");
cl.println("        }");
cl.println("");
if(digitalRead(io_jumper_illuminator1)==0 || digitalRead(io_jumper_illuminator2) == 0 || digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("        xlrToggle.onclick = toggle;");
cl.println("        xlrSwitch.onchange = xlrButton;");
}
cl.println("");
if(digitalRead(io_jumper_illuminator2) == 0 || digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("        zoomToggle.onclick = toggle; ");
cl.println("        angleWrappers[0].onclick = angleButton;");
cl.println("        angleWrappers[1].onclick = angleButton;");
cl.println("        angleWrappers[2].onclick = angleButton;");
}
cl.println("");
if(digitalRead(io_jumper_illuminator3) == 0 ){
cl.println("        hybridToggle.onclick = toggle;");
cl.println("        document.getElementById('irlight').onchange = hybridButton;");
cl.println("        document.getElementById('whiteLight').onchange = hybridButton;");
}
cl.println("");
cl.println("        ");
cl.println("        function toggle(){");
cl.println("          var node = controls[this.id]");
cl.println("            , text = this.innerHTML;");
cl.println("          for(var i = 0, len = drawers.length;i<len;i++){");
cl.println("            var pr = drawers[i];");
cl.println("            pr.className = (pr != controls[this.id] || pr.className.match('open'))? pr.className.replace('open', ''):pr.className+' open';");
cl.println("          }");
cl.println("        }");
cl.println("var nocache = 'cjifeh';");
cl.println("var _xlrPower ='';");
cl.println("var _button11   ='';");
cl.println("var _button21   ='';");
cl.println("var _button31   ='';");
cl.println("var _dayNight1  ='';");
cl.println("var _");
cl.println("var _zoomPower ='';");
cl.println("var _button12   ='';");
cl.println("var _button22   ='';");
cl.println("var _button32   ='';");
cl.println("var _dayNight2='';");
cl.println("var _");
cl.println("var _hybridPower ='';");
cl.println("var _button13   ='';");
cl.println("var _button23   ='';");
cl.println("var _button33   ='';");
cl.println("var _dayNight3='';");
cl.println("");
cl.println("var request = new XMLHttpRequest(); ");
cl.println("request.onreadystatechange = function() {");
cl.println("  if (this.readyState == 4 && this.status == 200) {");
cl.println("    if (this.responseXML != null) {");
cl.println("      //document.getElementById('xlrSwitch').checked = (this.responseXML.getElementsByTagName('buttonStatus11')[0].childNodes[0].nodeValue === 'on'); ");
cl.println("");
cl.println("      //var range = 0;");
cl.println("      //if (this.responseXML.getElementsByTagName('buttonStatus12')[0].childNodes[0].nodeValue === 'on') {range = 1}");
cl.println("      //if (this.responseXML.getElementsByTagName('buttonStatus22')[0].childNodes[0].nodeValue === 'on') {range = 2}");
cl.println("      //if (this.responseXML.getElementsByTagName('buttonStatus32')[0].childNodes[0].nodeValue === 'on') {range = 3}");
cl.println("      //console.log(this.responseXML.getElementsByTagName('buttonStatus12')[0].childNodes[0].nodeValue);");
cl.println("      //console.log(this.responseXML.getElementsByTagName('buttonStatus22')[0].childNodes[0].nodeValue);");
cl.println("      //console.log(this.responseXML.getElementsByTagName('buttonStatus32')[0].childNodes[0].nodeValue);");
cl.println("      //debugger;");
cl.println("      //angleWrappers[0].className = range==1? angleWrappers[0].className+' choosen':angleWrappers[0].className.replace(/choosen/g, '');");
cl.println("      //angleWrappers[1].className = range==2? angleWrappers[1].className+' choosen':angleWrappers[1].className.replace(/choosen/g, ''); ");
cl.println("      //angleWrappers[2].className = range==3? angleWrappers[2].className+' choosen':angleWrappers[2].className.replace(/choosen/g, ''); ");
cl.println("");
cl.println("");
cl.println("");
cl.println("      if (this.responseXML.getElementsByTagName('buttonStatus13')[0].childNodes[0].nodeValue === 'on') {");
cl.println("        document.getElementById('irlight').checked = true;");
cl.println("      } ");
cl.println("      if (this.responseXML.getElementsByTagName('buttonStatus23')[0].childNodes[0].nodeValue === 'on') {");
cl.println("        document.getElementById('whiteLight').checked = true;");
cl.println("      } ");
cl.println("    }");
cl.println("  }");
cl.println("}");
cl.println("");
cl.println("function XMLToString(oXML) {   ");
cl.println("  if (window.ActiveXObject) {     ");
cl.println("    return oXML.xml;  //if IE ");
cl.println("  } else {     ");
cl.println("  return (new XMLSerializer()).serializeToString(oXML);   ");
cl.println("  } ");
cl.println("}");
cl.println("");
cl.println("function GetArduinoIO() {");
cl.println("  nocache = '?nocache=' + Math.random() * 1000000;");
cl.println("  var path = 'ajax_inputs' + nocache + _xlrPower + _zoomPower + _hybridPower + _dayNight1 + _dayNight2 + _dayNight3 + _button11 + _button21 + _button31 + _button12 + _button22 + _button32 + _button13 + _button23 + _button33;");
cl.println("  console.log(path);");
cl.println("  request.open('GET', path, true);");
cl.println("  request.send(null);");
cl.println("  setTimeout('GetArduinoIO()', 1000);");
cl.println("");
cl.println("  _xlrPower ='';");
cl.println("  _button11   ='';");
cl.println("  _button21   ='';");
cl.println("  _button31   ='';");
cl.println("  _dayNight1  ='';");
cl.println("");
cl.println("  _zoomPower ='';");
cl.println("  _button12   ='';");
cl.println("  _button22   ='';");
cl.println("  _button32   ='';");
cl.println("  _dayNight2  ='';");
cl.println("");
cl.println("  _hybridPower ='';");
cl.println("  _button13   ='';");
cl.println("  _button23   ='';");
cl.println("  _button33   ='';");
cl.println("  _dayNight3  ='';");
cl.println("");
cl.println("}");
cl.println("");
cl.println("");
cl.println("function xlrButton(){");
cl.println(" _xlrPower = '&xlrPower=1';");
cl.println("  if(!this.checked){");
cl.println("    _button11 = '&button11=1';");
cl.println("  }else{ ");
cl.println("    _button11 = '&button11=0';");
cl.println("    _button31 = '&button31=1';");
cl.println("  }");
cl.println("}");
cl.println("");
cl.println("function angleButton(){");
cl.println("   angleWrappers[0].className = angleWrappers[0]==this? angleWrappers[0].className+' choosen':angleWrappers[0].className.replace(/choosen/g, '');");
cl.println("   angleWrappers[1].className = angleWrappers[1]==this? angleWrappers[1].className+' choosen':angleWrappers[1].className.replace(/choosen/g, '');");
cl.println("   angleWrappers[2].className = angleWrappers[2]==this? angleWrappers[2].className+' choosen':angleWrappers[2].className.replace(/choosen/g, '');");
cl.println("   //platform feedback");
cl.println("   if(this.id=='angle1'){ _button12 = '&button12=1'; _zoomPower = '&zoomPower=1';}");
cl.println("   else if(this.id=='angle2'){ _button22 = '&button22=1';_zoomPower = '&zoomPower=1';}");
cl.println("   else{ _button32 = '&button32=1';_zoomPower = '&zoomPower=1';}");
cl.println("}");
cl.println("");
cl.println("function hybridButton(){");
cl.println(" _hybridPower = '&hybridPower=1'");
cl.println("  if(this.id=='irlight') _button13 = '&button13=1';");
cl.println("  else _button23 = '&button23=1'; ");
cl.println("}");
cl.println("        GetArduinoIO();");
cl.println("      </script>");
cl.println("    </body>");
cl.println("</html>");
}

