void printWebPage(EthernetClient cl){
  cl.println("<!DOCTYPE html> ");
  cl.println("<html>");
  cl.println("    <head>");
  cl.println("        <title>AxtonTech Illumnate the Night</title>");
  cl.println("        <script>");
  cl.println("          _degree10        = '';");
  cl.println("      	_degree45        = '';");
  cl.println("      	_degree130       = '';");
  cl.println("          _power           = '';");
  cl.println("          _whiteLight      = '';");
  cl.println("          _irLight         = '';");

  cl.println("          _degree10_state   = 0;");
  cl.println("          _degree45_state   = 0;");
  cl.println("          _degree130_state  = 0;");
  cl.println("          _power_state      = 0;");
  cl.println("          _whiteLight_state = 0;");
  cl.println("          _irLight_state    = 0;");

  cl.println("          function XMLToString(oXML) {   ");
  cl.println("              if (window.ActiveXObject) {     ");
  cl.println("                  return oXML.xml;  //if IE ");
  cl.println("              } else {     ");
  cl.println("                  return (new XMLSerializer()).serializeToString(oXML);   //other browsers");
  cl.println("              } ");
  cl.println("          }");
  cl.println("      		function GetArduinoIO()");
  cl.println("      		{");
  cl.println("      			nocache = '&nocache=' + Math.random() * 1000000;");
  cl.println("      			var request = new XMLHttpRequest();");
  cl.println("      			request.onreadystatechange = function()");
  cl.println("      			{");
  cl.println("      				if (this.readyState == 4) {");
  cl.println("      					if(this.status == 200) {");
  cl.println("      						if (this.responseXML != null) {");
  cl.println("         							if (this.responseXML.getElementsByTagName('power')[0].childNodes[0].nodeValue === 'off') {");
  cl.println("      								_power_state      = 0;");
  cl.println("      								_degree10_state   = 0;");
  cl.println("      								_degree45_state   = 0;");
  cl.println("      								_degree130_state  = 0;");
  cl.println("      								_whiteLight_state = 0;");
  cl.println("      								_irLight_state    = 0;");
  cl.println("          						        document.getElementById('degree10'  ).innerHTML = 'Zoom 10&deg Off';");
  cl.println("          							document.getElementById('degree45'  ).innerHTML = 'Zoom 30&deg Off';");
  cl.println("          							document.getElementById('degree130' ).innerHTML = 'Zoom 60&deg Off';");
  cl.println("      								document.getElementById('power'     ).innerHTML = 'Power Off';");
  cl.println("      								document.getElementById('whiteLight').innerHTML = 'White Light Off';");
  cl.println("      								document.getElementById('irLight'   ).innerHTML = 'IR Off';");
  cl.println("      							}else{");
  cl.println("      								  _power_state = 1;");
  cl.println("      								  document.getElementById('power').innerHTML = 'Power On';");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree10')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree10').innerHTML = 'Zoom 10&deg On';");
  cl.println("          								_degree10_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree10').innerHTML = 'Zoom 10&deg Off';");
  cl.println("          								_degree10_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree45')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree45').innerHTML = 'Zoom 30&deg On';");
  cl.println("          								_degree45_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree45').innerHTML = 'Zoom 30&deg Off';");
  cl.println("          								_degree45_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('degree130')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('degree130').innerHTML = 'Zoom 60&deg On';");
  cl.println("          								_degree130_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('degree130').innerHTML = 'Zoom 60&deg Off';");
  cl.println("          								_degree130_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('whiteLight')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('whiteLight').innerHTML = 'White Light On';");
  cl.println("          								_whiteLight_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('whiteLight').innerHTML = 'White Light Off';");
  cl.println("          								_whiteLight_state = 0;");
  cl.println("          							}");
  cl.println("          							if (this.responseXML.getElementsByTagName('irLight')[0].childNodes[0].nodeValue === 'on') {");
  cl.println("          								document.getElementById('irLight').innerHTML = 'IR On';");
  cl.println("          								_irLight_state = 1;");
  cl.println("          							}");
  cl.println("          							else {");
  cl.println("          								document.getElementById('irLight').innerHTML = 'IR Off';");
  cl.println("          								_irLight_state = 0;");
  cl.println("          							}");
  cl.println("      						        }");
  cl.println("      ");
  cl.println("      						}");
  cl.println("      					}");
  cl.println("      				}");
  cl.println("      			}");
  cl.println("      			// send HTTP GET request with LEDs to switch on/off if any");
  cl.println("      			request.open('GET', 'ajax_inputs' + _degree10 + _degree45 + _degree130 + _power + _whiteLight + _irLight + nocache, true);");
  cl.println("      			request.send(null);");
  cl.println("      			setTimeout('GetArduinoIO()', 1000);");
  cl.println("        		        _degree10    = '';");
  cl.println("      	  	        _degree45    = '';");
  cl.println("      		        _degree130   = '';");
  cl.println("                          _power       = '';");
  cl.println("                          _whiteLight  = '';");
  cl.println("                          _irLight     = '';");
  cl.println("      ");
  cl.println("      		}");
  cl.println("      ");
  cl.println("      		function GetButtonPower()");
  cl.println("      		{");
  cl.println("        			if (_power_state === 1) {");
  cl.println("        				_power_state = 0;");
  cl.println("        				_power = '&power=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_power_state = 1;");
  cl.println("        				_power = '&power=1';");
  cl.println("        			}");
  cl.println("      		}");
  cl.println("                  function GetButton10(){");
  cl.println("        			if (_degree10_state === 1) {");
  cl.println("        				_degree10_state = 0;");
  cl.println("        				_degree10 = '&degree10=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree10_state = 1;");
  cl.println("        				_degree10 = '&degree10=1';");
  cl.println("        			}");
  cl.println("                  }");
  cl.println("                  function GetButton45(){");
  cl.println("        			if (_degree45_state === 1) {");
  cl.println("        				_degree45_state = 0;");
  cl.println("        				_degree45 = '&degree45=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree45_state = 1;");
  cl.println("        				_degree45 = '&degree45=1';");
  cl.println("        			}");
  cl.println("                  }");
  cl.println("                  function GetButton130(){");
  cl.println("        			if (_degree130_state === 1) {");
  cl.println("        				_degree130_state = 0;");
  cl.println("        				_degree130 = '&degree130=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_degree130_state = 1;");
  cl.println("        				_degree130 = '&degree130=1';");
  cl.println("        			}");
  cl.println("                  }");
  cl.println("                  function GetButtonWhiteLight(){");
  cl.println("        			if (_whiteLight_state === 1) {");
  cl.println("        				_whiteLight_state = 0;");
  cl.println("        				_whiteLight = '&whiteLight=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_whiteLight_state = 1;");
  cl.println("        				_whiteLight = '&whiteLight=1';");
  cl.println("        			}");
  cl.println("                  }");
  cl.println("                  function GetButtonIRLight(){");
  cl.println("        			if (_irLight_state === 1) {");
  cl.println("        				_irLight_state = 0;");
  cl.println("        				_irLight = '&irLight=0';");
  cl.println("        			}");
  cl.println("        			else {");
  cl.println("        				_irLight_state = 1;");
  cl.println("        				_irLight = '&irLight=1';");
  cl.println("        			}");
  cl.println("                  }");
  cl.println("	      </script>");

  cl.println("	<style>");
  cl.println("		.IO_box {");
  cl.println("			align  : left;");
  cl.println("			margin : 0 20px 20px 0;");
  cl.println("			border : 1px solid white;");
  cl.println("			padding: 0 5px 0 5px;");
  cl.println("			width  : 180px;");
  cl.println("		}");
  cl.println("		h1 {");
  cl.println("			font-family: arial, sans-serif;font-size: 120%;");
  cl.println("			color: #46af00;");
  cl.println("			margin: 0 0 10px 0;");
  cl.println("		}");
  cl.println("		h2 {");
  cl.println("			font-family: arial, sans-serif;font-size: 85%;");
  cl.println("			color: #46af00;");
  cl.println("			margin: 5px 0 5px 0;");
  cl.println("		}");
  cl.println("		p, form, button {");
  cl.println("			font-size: 80%;");
  cl.println("			color: #252525;");
  cl.println("		}");
  cl.println("		.small_text {");
  cl.println("			font-size: 70%;");
  cl.println("			color: #737373;");
  cl.println("		}");
  cl.println("          .powerRed{");
  cl.println("	            background-color:red;");
  cl.println("	            color:white;");
  cl.println("	        }");
  cl.println("          .powerGreen{");
  cl.println("	            background-color:green;");
  cl.println("	            color:white;");
  cl.println("	        }");
  cl.println("	</style>");
  cl.println("    </head>");

  cl.println("<img style='float:left' src='data:image/png;base64,");
  for (int i=0;i<21;i++){
    cl.write(logo_raw[i]);
  }
  cl.println("'> ");                     
  cl.println("<p>");
  cl.println("    <body onload='GetArduinoIO()'>");
  cl.println("		<div class='IO_box' >");
  getModel();
  cl.println("             <h1>" + model + " </h1><h2>(Variable Angles)</h2>");
  cl.println("			<button type='button' class='power'  id='power'     onclick='GetButtonPower()'>I/O (Off)        </button><br /><br />");
  cl.println("                  <hr>");
  cl.println("			<h2>Illumination Controls</h2>");
  cl.println("				<button type='button' class='degree' id='degree10'  onclick='GetButton10()'   >Angle 10&deg Off  </button><br /><br />");
  cl.println("				<button type='button' class='degree' id='degree45'  onclick='GetButton45()'   >Angle 30&deg Off  </button><br /><br />");
  cl.println("				<button type='button' class='degree' id='degree130' onclick='GetButton130()'  >Angle 60&deg Off  </button><br /><br />");
  cl.println("		</div>");

  cl.println("		<div class='IO_box' >");
  cl.println("             <h1>Hybrid </h1><h2>(White & IR)</h2>");
  cl.println("				<button type='button' class='power2'  id='power2'     onclick='GetButtonPower()'>I/O (Off)       </button><br /><br />");
  cl.println("<hr>");
  cl.println("			<h2>Illumination Controls</h2>");
  cl.println("				<button type='button' class='degree' id='whiteLight' onclick='GetButtonWhiteLight()' >White Light Off  </button><br /><br />");
  cl.println("				<button type='button' class='degree' id='irLight'    onclick='GetButtonIRLight()'    >IR Off           </button><br /><br />");
  cl.println("		</div>");

  cl.println("    </body>");
  cl.println("</html>");
}

